apiVersion: v1
kind: Service
metadata:
  name: vector-database-service
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: vector-database-0
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
