syntax = "proto3";

package vector_db;

service VectorDatabase {
  rpc Insert(InsertRequest) returns (InsertResponse);
  rpc Remove(RemoveRequest) returns (RemoveResponse);
  rpc Search(SearchRequest) returns (SearchResponse);
  rpc Stats(StatsRequest) returns (StatsResponse);
  rpc Metrics(MetricsRequest) returns (MetricsResponse);
  rpc CreateTable(CreateTableRequest) returns (CreateTableResponse);

  rpc HealthCheck(Empty) returns (Status);
}

message InsertRequest {
  uint64 id = 1;
  repeated float vector = 2;
  string content = 3;
}

message InsertResponse {
  bool successful = 1;
}

message RemoveRequest{
  uint64 id = 1;
}

message RemoveResponse {
  bool successful = 1;
}

message SearchRequest {
  repeated float query = 1;
  uint32 k = 2;
  uint32 search_parameter = 3;
}

message SearchResponse {
  message Data {
    uint64 id = 1;
    string content = 2;
  }
  repeated Data data = 1;
}

message Empty {}

message Status {
  bool successful = 1;
  string message = 2;
}

message StatsRequest {}

message StatsResponse {
  uint64 vector_count = 1;
  uint64 deleted_count = 2;
  uint64 stale_count = 3;
}

message MetricsRequest {}

message MetricsResponse {
  uint64 insert_count = 1;
  uint64 remove_count = 2;
  uint64 search_count = 3;
  uint64 cleanup_count = 4;
  uint64 reindex_count = 5;

  uint64 average_search_latency_ms = 6;
}

message CreateTableRequest {
  string name = 1;
}

message CreateTableResponse {
  bool successful = 1;
}
