syntax = "proto3";

package vector_db;

service VectorDatabase {
  rpc Insert(InsertRequest) returns (InsertResponse);
  rpc Remove(RemoveRequest) returns (RemoveResponse);
  rpc Search(SearchRequest) returns (SearchResponse);

  rpc BatchInsert(BatchInsertRequest) returns (BatchInsertResponse);
  rpc BatchRemove(BatchRemoveRequest) returns (BatchRemoveResponse);
  rpc BatchSearch(BatchSearchRequest) returns (BatchSearchResponse);

  rpc Stats(StatsRequest) returns (StatsResponse);
  rpc Metrics(MetricsRequest) returns (MetricsResponse);

  rpc CreateTable(CreateTableRequest) returns (CreateTableResponse);
  rpc DropTable(DropTableRequest) returns (DropTableResponse);

  rpc HealthCheck(Empty) returns (Status);
}

message InsertRequest {
  uint64 id = 1;
  repeated float vector = 2;
  string content = 3;

  string table = 4;
}

message InsertResponse {
  bool successful = 1;
}

message RemoveRequest{
  uint64 id = 1;

  string table = 2;
}

message RemoveResponse {
  bool successful = 1;
}

message SearchRequest {
  repeated float query = 1;
  uint32 k = 2;
  uint32 search_parameter = 3;

  string table = 4;
}

message SearchResponse {
  message Data {
    uint64 id = 1;
    string content = 2;
  }
  repeated Data data = 1;
}

message BatchInsertRequest {
  message VectorData {
    uint64 id = 1;
    repeated float vector = 2;
    string content = 3;
  }
  repeated VectorData vector_data = 1;

  string table = 2;
}

message BatchInsertResponse {
  repeated bool successful = 1;
}

message BatchRemoveRequest{
  repeated uint64 id = 1;

  string table = 2;
}

message BatchRemoveResponse {
  repeated bool successful = 1;
}

message BatchSearchRequest {
  message Query {
    repeated float query = 1;
    uint32 k = 2;
    uint32 search_parameter = 3;
  }

  repeated Query query = 1;
  string table = 2;
}

message BatchSearchResponse {
  message Result {
    message Data {
      uint64 id = 1;
      string content = 2;
    }
    repeated Data data = 1;
  }

  repeated Result result = 1;
}

message Empty {}

message Status {
  bool successful = 1;
  string message = 2;
}

message StatsRequest {
  string table = 1;
}

message StatsResponse {
  uint64 vector_count = 1;
  uint64 deleted_count = 2;
  uint64 stale_count = 3;
}

message MetricsRequest {
  string table = 1;
}

message MetricsResponse {
  uint64 insert_count = 1;
  uint64 remove_count = 2;
  uint64 search_count = 3;
  uint64 cleanup_count = 4;
  uint64 reindex_count = 5;

  float average_search_latency_ms = 6;
  float max_search_latency_ms = 7;
  float min_search_latency_ms = 8;

  uint64 cache_hit = 9;
  uint64 cache_miss = 10;
}

message CreateTableRequest {
  string name = 1;

  message StoreConfig {
    int32 vector_dimensionality = 1;
  }

  StoreConfig store_config = 2;

  message HNSWIndexConfig {
    uint64 m = 1;
    uint64 m0 = 2;
    uint64 ef_construction = 3;
    float ml = 4;
    int32 vector_dimensionality = 5;

    enum DistanceMetric {
      L2 = 0;
      COSINE = 1;
    }

    DistanceMetric distance_metric = 6;
  }

  oneof index_config {
    HNSWIndexConfig hnsw_index_config = 3;
  }

  message CacheConfig {
    uint64 cache_size = 1;
  }

  CacheConfig cache_config = 4;
}

message CreateTableResponse {
  bool successful = 1;
}

message DropTableRequest {
  string name = 1;
}

message DropTableResponse {
  bool successful = 1;
}
